# Use root/example as user/password credentials
version: '3.1'

services:

  rdbm:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - /home/samsepi0l/.shared/docker:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8800:8080
