insert into `region` (`id`, `country`, `name`) values (1, 'Espana', 'Toro');
insert into `region` (`id`, `country`, `name`) values (2, 'Espana', 'Vino de Espana');
insert into `region` (`id`, `country`, `name`) values (3, 'Espana', 'Ribera del Duero');
insert into `region` (`id`, `country`, `name`) values (4, 'Espana', 'Montilla-Moriles');
insert into `region` (`id`, `country`, `name`) values (5, 'Espana', 'Jumilla');
insert into `region` (`id`, `country`, `name`) values (6, 'Espana', 'Jerez-Xeres-Sherry');
insert into `region` (`id`, `country`, `name`) values (7, 'Espana', 'Priorato');
insert into `region` (`id`, `country`, `name`) values (8, 'Espana', 'Rioja');
insert into `region` (`id`, `country`, `name`) values (9, 'Espana', 'Bierzo');
insert into `region` (`id`, `country`, `name`) values (10, 'Espana', 'Castilla y Leon');
insert into `region` (`id`, `country`, `name`) values (11, 'Espana', 'Campo de Borja');
insert into `region` (`id`, `country`, `name`) values (12, 'Espana', 'Cadiz');
insert into `region` (`id`, `country`, `name`) values (13, 'Espana', 'Cava');
insert into `region` (`id`, `country`, `name`) values (14, 'Espana', 'Jerez Palo Cortado');
insert into `region` (`id`, `country`, `name`) values (15, 'Espana', 'Manzanilla');
insert into `region` (`id`, `country`, `name`) values (16, 'Espana', 'Valdeorras');
insert into `region` (`id`, `country`, `name`) values (17, 'Espana', 'Emporda');
insert into `region` (`id`, `country`, `name`) values (18, 'Espana', 'Rioja Alta');
insert into `region` (`id`, `country`, `name`) values (19, 'Espana', 'Alicante');
insert into `region` (`id`, `country`, `name`) values (20, 'Espana', 'Somontano');
insert into `region` (`id`, `country`, `name`) values (21, 'Espana', 'Dominio de Valdepusa');
insert into `region` (`id`, `country`, `name`) values (22, 'Espana', 'Ribeiro');
insert into `region` (`id`, `country`, `name`) values (23, 'Espana', 'Mallorca');
insert into `region` (`id`, `country`, `name`) values (24, 'Espana', 'Yecla');
insert into `region` (`id`, `country`, `name`) values (25, 'Espana', 'Cigales');
insert into `region` (`id`, `country`, `name`) values (26, 'Espana', 'Utiel-Requena');
insert into `region` (`id`, `country`, `name`) values (27, 'Espana', 'Navarra');
insert into `region` (`id`, `country`, `name`) values (28, 'Espana', 'Rioja Alavesa');
insert into `region` (`id`, `country`, `name`) values (29, 'Espana', 'Costers del Segre');
insert into `region` (`id`, `country`, `name`) values (30, 'Espana', 'Sardon de Duero');
insert into `region` (`id`, `country`, `name`) values (31, 'Espana', 'Malaga');
insert into `region` (`id`, `country`, `name`) values (32, 'Espana', 'Cataluna');
insert into `region` (`id`, `country`, `name`) values (33, 'Espana', 'Rueda');
insert into `region` (`id`, `country`, `name`) values (34, 'Espana', 'Jerez Pedro Ximenes (PX)');
insert into `region` (`id`, `country`, `name`) values (35, 'Espana', 'Tierra del Vino de Zamora');
insert into `region` (`id`, `country`, `name`) values (36, 'Espana', 'Penedes');
insert into `region` (`id`, `country`, `name`) values (37, 'Espana', 'Jerez Amontillado');
insert into `region` (`id`, `country`, `name`) values (38, 'Espana', 'Conca de Barbera');
insert into `region` (`id`, `country`, `name`) values (39, 'Espana', 'Almansa');
insert into `region` (`id`, `country`, `name`) values (40, 'Espana', 'Castilla');
insert into `region` (`id`, `country`, `name`) values (41, 'Espana', 'Rias Baixas');
insert into `region` (`id`, `country`, `name`) values (42, 'Espana', 'Montsant');
insert into `region` (`id`, `country`, `name`) values (43, 'Espana', 'Valencia');
insert into `region` (`id`, `country`, `name`) values (44, 'Espana', 'Andalucia');
insert into `region` (`id`, `country`, `name`) values (45, 'Espana', 'Monterrei');
insert into `region` (`id`, `country`, `name`) values (46, 'Espana', 'Carinena');
insert into `region` (`id`, `country`, `name`) values (47, 'Espana', 'Ribera del Gallego-Cinco Villas');
insert into `region` (`id`, `country`, `name`) values (48, 'Espana', 'Ribeira Sacra');
insert into `region` (`id`, `country`, `name`) values (49, 'Espana', 'Pla i Llevant');
insert into `region` (`id`, `country`, `name`) values (50, 'Espana', 'Pago Calzadilla');
insert into `region` (`id`, `country`, `name`) values (51, 'Espana', 'La Mancha');
insert into `region` (`id`, `country`, `name`) values (52, 'Espana', 'Terra Alta');
insert into `region` (`id`, `country`, `name`) values (53, 'Espana', 'Arribes');
insert into `region` (`id`, `country`, `name`) values (54, 'Espana', 'Galicia');
insert into `region` (`id`, `country`, `name`) values (55, 'Espana', 'Mentrida');
insert into `region` (`id`, `country`, `name`) values (56, 'Espana', 'Gran Canaria');
insert into `region` (`id`, `country`, `name`) values (57, 'Espana', 'Abona');
insert into `region` (`id`, `country`, `name`) values (58, 'Espana', 'Tarragona');
insert into `region` (`id`, `country`, `name`) values (59, 'Espana', 'El Terrerazo');
insert into `region` (`id`, `country`, `name`) values (60, 'Espana', 'Sierras de Malaga');
insert into `region` (`id`, `country`, `name`) values (61, 'Espana', 'Pla de Bages');
insert into `region` (`id`, `country`, `name`) values (62, 'Espana', 'Jerez Oloroso');
insert into `region` (`id`, `country`, `name`) values (63, 'Espana', 'Extremadura');
insert into `region` (`id`, `country`, `name`) values (64, 'Espana', 'Alella');
insert into `region` (`id`, `country`, `name`) values (65, 'Espana', 'Valdejalon');
insert into `region` (`id`, `country`, `name`) values (66, 'Espana', 'Otazu');
insert into `region` (`id`, `country`, `name`) values (67, 'Espana', 'Arinzano');
insert into `region` (`id`, `country`, `name`) values (68, 'Espana', 'La Palma');
insert into `region` (`id`, `country`, `name`) values (69, 'Espana', 'Murcia');
insert into `region` (`id`, `country`, `name`) values (70, 'Espana', 'Madrid');
insert into `region` (`id`, `country`, `name`) values (71, 'Espana', 'Calatayud');
insert into `region` (`id`, `country`, `name`) values (72, 'Espana', 'Aragon');
insert into `region` (`id`, `country`, `name`) values (73, 'Espana', 'Binissalem-Mallorca');
insert into `region` (`id`, `country`, `name`) values (74, 'Espana', 'Jerez Cream');
insert into `region` (`id`, `country`, `name`) values (75, 'Espana', 'Dehesa del Carrizal');
insert into `region` (`id`, `country`, `name`) values (76, 'Espana', 'Condado de Huelva');
