insert into `type` (`id`, `name`) values (1, 'Toro Red');
insert into `type` (`id`, `name`) values (2, 'Tempranillo');
insert into `type` (`id`, `name`) values (3, 'Ribera Del Duero Red');
insert into `type` (`id`, `name`) values (4, 'Pedro Ximenez');
insert into `type` (`id`, `name`) values (5, 'Red');
insert into `type` (`id`, `name`) values (6, 'Sherry');
insert into `type` (`id`, `name`) values (7, 'Priorat Red');
insert into `type` (`id`, `name`) values (8, 'Rioja Red');
insert into `type` (`id`, `name`) values (9, 'Rioja White');
insert into `type` (`id`, `name`) values (10, 'Grenache');
insert into `type` (`id`, `name`) values (11, 'NA');
insert into `type` (`id`, `name`) values (12, 'Cava');
insert into `type` (`id`, `name`) values (13, 'Verdejo');
insert into `type` (`id`, `name`) values (14, 'Syrah');
insert into `type` (`id`, `name`) values (15, 'Monastrell');
insert into `type` (`id`, `name`) values (16, 'Mencia');
insert into `type` (`id`, `name`) values (17, 'Sparkling');
insert into `type` (`id`, `name`) values (18, 'Chardonnay');
insert into `type` (`id`, `name`) values (19, 'Albarino');
insert into `type` (`id`, `name`) values (20, 'Montsant Red');
insert into `type` (`id`, `name`) values (21, 'Cabernet Sauvignon');
insert into `type` (`id`, `name`) values (22, 'Sauvignon Blanc');
